import { render, screen } from '@testing-library/react';

import RootLayout, { metadata } from './layout';

describe('Root Layout', () => {
  // ignore error about <html> tag in <div>
  // "render" attaches the element to the document.body,
  // but this is the root layout, so ignore error
  console.error = jest.fn();

  it('should render successfully', () => {
    render(
      RootLayout({
        children: <p>Hello World!</p>,
      })
    );
    expect(screen.getByText('Hello World!')).toBeDefined();
  });

  it('should have title and description in metadata', () => {
    expect(metadata.title).toBe('Welcome to map-lab-next');
    expect(metadata.description).toBe('Generated by create-nx-workspace');
  });
});
